[colors]
[colors.primary]
background = '#282635'
foreground = '#ffeecc'

# Normal colors
[colors.normal]
black = '#2c2a3b'
red = '#ff6570'
green = '#00d6b9'
yellow = '#ffd47f'
blue = '#1980a3'
magenta = '#c66b9a'
cyan = '#00d6b9'
white = '#ece8d6'

# Bright colors
[colors.bright]
black = '#46425e'
red = '#ffab9e'
green = '#00eacb'
yellow = '#ffeecc'
blue = '#21a7d3'
magenta = '#dba2c0'
cyan = '#00eacb'
white = '#fbf6e4'

[colors.selection]
background = '#46425e'

[colors.cursor]
cursor = '#ff6973'
text = '#ffffff'

